//
//  AlbumModels.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias PhotoCellViewModel = Album.ShowAlbum.ViewModel.PhotoCell

protocol CellIdentifiable {
    var cellIdentifier: String { get }
}

enum Album {
    
    enum ShowAlbum {
        
        struct Response {
            let album: AlbumResponse?
        }
        
        struct ViewModel {
            struct PhotoCell: CellIdentifiable {
                let imageUrl: String?
                
                var cellIdentifier: String {
                    "Cell"
                }
                
                init(photo: Photo) {
                    imageUrl = photo.imgSrc
                }
            }
            let items: [CellIdentifiable]
        }
    }
}
