//
//  AlbumInteractor.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumBusinessLogic {
    func fetchAlbum()
}

protocol AlbumDataStore {
    var album: AlbumResponse? { get }
}

class AlbumInteractor: AlbumBusinessLogic, AlbumDataStore {

    private let networkManager = NetworkManager(networkComponents: NetworkComponents())
    var album: AlbumResponse?
    var presenter: AlbumPresentationLogic?
    
    func fetchAlbum() {
        networkManager.getAlbum { [weak self] albumResponse in
            self?.album = albumResponse
            let response = Album.ShowAlbum.Response(album: albumResponse)
            self?.presenter?.presentAlbum(response: response)
        }
    }
    
}
