//
//  AlbumPresenter.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumPresentationLogic {
    func presentAlbum(response: Album.ShowAlbum.Response)
}

class AlbumPresenter: AlbumPresentationLogic {
    
    weak var viewController: AlbumDisplayLogic?
    
    // MARK: Do something
    
    func presentAlbum(response: Album.ShowAlbum.Response) {
        
        let items = response.albumResponse?.items.count ?? 0
        
        let viewModel = Album.ShowAlbum.ViewModel(
            count: items,
            items: response.albumResponse?.items ?? []
        )
        viewController?.displayAlbum(viewModel: viewModel)

    }
}
