//
//  AlbumInteractor.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumBusinessLogic {
    func fetchAlbum()
}

protocol AlbumDataStore {
    var album: AlbumResponse? { get }
}

class AlbumInteractor: AlbumBusinessLogic, AlbumDataStore {
    
    private let networkManager = NetworkManager(networkComponents: NetworkComponents())
    var album: AlbumResponse?
    var presenter: AlbumPresentationLogic?

    func fetchAlbum() {
        networkManager.getAlbum { (album) in
            self.album = album
            let response = Album.ShowAlbum.Response(albumResponse: album)
            self.presenter?.presentAlbum(response: response)
        }
    }
    
}
