//
//  AlbumModels.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Album {
    // MARK: Use cases
    
    enum ShowAlbum {
        struct Request {}
        
        struct Response {
            let albumResponse: AlbumResponse?
        }
        
        struct ViewModel {
            var count: Int
            var items: [Photo]
        }
    }
}
