//
//  PhotoModels.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotoItem {

    enum ShowItem {
        
        struct Request {}
        
        struct Response {
            var date: Int
            var sizes: [PhotoSizes]
            var imgSrc: String {
                self.getSize().url
            }

            private func getSize() -> PhotoSizes{
                if let sizeX = sizes.first(where: { $0.type == "x"}) {
                    return sizeX
                } else if let bigSize = sizes.last {
                    return bigSize
                } else {
                    return PhotoSizes(type: "wrong type", url: "wrong url")
                }
            }
        }
        
        struct ViewModel {
            var date: Int
            var sizes: [PhotoSizes]
            var imgSrc: String
        }
    }
}
