//
//  PhotoInteractor.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoBusinessLogic {
    func getPhoto()
}

protocol PhotoDataStore {
    var photo: Photo? { get }
}

class PhotoInteractor: PhotoBusinessLogic, PhotoDataStore {
    private let networkManager = NetworkManager(networkComponents: NetworkComponents())
    var photo: Photo?
    
    var presenter: PhotoPresentationLogic?
    
    // MARK: Do something
    
    func getPhoto() {
        
        networkManager.getAlbum { [weak self] album in
            
//            self?.album = albumResponse
//            let response = Album.ShowAlbum.Response(album: albumResponse)
//            self?.presenter?.presentAlbum(response: response)
        }
    }
}
