//
//  PhotoPresenter.swift
//  VKPhotoViewer
//
//  Created by PenguinRaja on 01.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoPresentationLogic {
    func presentSomething(response: PhotoItem.ShowItem.Response)
}

class PhotoPresenter: PhotoPresentationLogic {
    
    weak var viewController: PhotoDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: PhotoItem.ShowItem.Response) {
        let viewModel = PhotoItem.ShowItem.ViewModel(date: 1, sizes: [])
        viewController?.displayPhotoDetails(viewModel: viewModel)
    }
}
